### ISSUE TITLE
redisplay error: Note type error at frontmatter

### ISSUE THREAD

**Issue by mattly** [Sorixelle/astro-ts-mode#10]
so, I don't know if this is a problem with emacs 29.3's treesit or astro-ts-mode, or what, but I'm consisitently getting this error when attempting to enable `astro-ts-mode` on *any* astro file: 
```
redisplay--pre-redisplay-functions: (treesit-query-error "Node type error at" 32 "(frontmatter (raw_text) @cap) (interpolation (raw_text) @cap) (script_element (raw_text) @cap)" "Debug the query with `treesit-query-validate'")
```

I've ruled out treesit-auto, I've ensured I'm using the same version of the treesitter grammar that I'm using in other editors, where it works fine. Any ideas?

**Comment by te-sh** [comment]
I meet the same problem.

**Comment by Sorixelle** [comment]
Duplicate of #9 - tracking there.
