### ISSUE TITLE
Syntax highlighting issue. 

### ISSUE THREAD

**Issue by tian-yi** [Sorixelle/astro-ts-mode#4]
Hi, 

First, I'd like to thank you for making this mode. 
I've just started learning Astro, and I am glad someone has already made a mode for it. 

I've followed the instructions to set up Astro mode, and everything works fine, except the highlighting is a bit off for some reason.
Please see the screenshot below. And if you can point me in the right direction, I am willing to do some work contributing to this project. 

Again, thanks for making this. Save me the misery of using VScode
<img width="1494" alt="Screenshot 2023-07-19 at 22 27 17" src="https://github.com/Sorixelle/astro-ts-mode/assets/1011678/6a5f1270-ae92-4143-ba44-99a750cb5ae1">

**Comment by Sorixelle** [comment]
I'm unable to reproduce this consistently, unfortunately - I have seen issues like this crop up in my own use from time to time, although I've not yet been able to determine the exact issues. Multi-language support (ie. Astro base, with Typescript and CSS portions) in treesit.el is pretty flaky, and quite buggy at the moment. There's a few bugs I've found that I need to report to emacs upstream, and hopefully some of those should work around those issues. For now though, unfortunately I'm not 100% sure what can be done to resolve this.

**Comment by tian-yi** [comment]
No problem. Thanks!
