### ISSUE TITLE
Error during redisplay: (jit-lock-function 1) signaled (treesit-query-error "Node type error at" 2 "

### ISSUE THREAD

**Issue by FilConscious** [Sorixelle/astro-ts-mode#9]
Hi Sorixelle,

Thanks a lot for the package. I have followed your installation instructions without any errors, specifically:

- installed from MELPA
- manually installed the grammars using `treesit-install-language-grammar`

When I open a `.astro` file the major mode is not detected (it remains `Fundamental` in the mode line) but it is activated if I do `M-x astro-ts-mode` (I see the change in the mode line). However, no code is highlighted and tree-sitter throws the error below:

![Screenshot from 2024-03-05 09-37-13](https://github.com/Sorixelle/astro-ts-mode/assets/56924093/a23ac842-44c8-41d9-af80-a9ba6d2223e3)

Any help would be really appreciated.

**Comment by Sorixelle** [comment]
Are you able to provide an `.astro` file that reproduces this issue?

**Comment by zetashift** [comment]
I'm running into this as well, I believe the `tree-sitter-astro` changed in a way that the queries don't work. 
This errors pops up for me from the most basic of astro files :

```astro
---
interface Props {
  title: string;
}

const { title } = Astro.props;
---

<!doctype html>
<html lang="en" data-theme="pastel">
  <head>
    <meta charset="UTF-8" />
    <meta name="description" content="Astro description" />
    <meta name="viewport" content="width=device-width" />
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
    <link rel="manifest" href="/site.webmanifest" />
    <meta name="generator" content={Astro.generator} />
    <title>{title}</title>
  </head>
  <body class="scroll-smooth">
    <slot />
  </body>
</html>
```

**Comment by g7s** [comment]
Same here, even with the placeholder `index.astro`

```astro
---
// Welcome to Astro! Everything between these triple-dash code fences
// is your "component frontmatter". It never runs in the browser.
console.log('This runs in your terminal, not the browser!');
---

<!-- Below is your "component template." It's just HTML, but with
     some magic sprinkled in to help you build great templates. -->
<html>
  <body>
    <h1>Hello, World!</h1>
  </body>
</html>

<style>
  h1 {
    color: orange;
  }
</style>
```

Does anyone have any workarounds?

**Comment by Sorixelle** [comment]
Sorry for taking such a long time to get back to this one. It seems that the upstream tree-sitter grammar renamed a few nodes since I last worked on this mode. I've pushed an update that should fix this issue. Please comment/reopen if there's still any issues after pulling the latest version.

**Comment by ckruse** [comment]
Hu? Where did you push such changes, Elpa? :-)

**Comment by Sorixelle** [comment]
They're on master on this repo. Doesn't looks like MELPA has picked it up yet (although MELPA Stable has, funnily enough), but that should happen hopefully in the next few hours or so.

**Comment by ckruse** [comment]
You see me confused. When I look at the master commit history, I get the last commit 10 months ago:

![image](https://github.com/user-attachments/assets/16420f27-6d14-43d7-8554-a53983b86262)

Am I missing something?

**Comment by mmarx** [comment]
> Doesn't looks like MELPA has picked it up yet (although MELPA Stable has, funnily enough)

The [commit](https://github.com/Sorixelle/astro-ts-mode/tree/78e7e942011839bd4f4de0a1d8460f5879ba4ca5) doesn't seem to be part of the `main` branch:
> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

**Comment by Sorixelle** [comment]
...ahahaha, so I put a copy of this repo on [my personal Forgejo instance](https://git.isincredibly.gay/srxl/astro-ts-mode) and setup a sync job from Forgejo -> GitHub, but I forgot to update the remote on my local checkout, so I pushed it here, and then Forgejo wiped the commit when it ran it's scheduled sync :sweat_smile: I've fixed that up now, should be actually live. Sorry about that!

**Comment by ckruse** [comment]
Nice, thank you very much :-)
